"""
Slice each location decor pack (RGBA, already alpha-fixed) into individual
tightly-cropped object sprites via connected-component labeling on the
alpha channel, instead of relying on a fixed slot grid (which produced
wrong-scale / cropped results once packs got resized for the artifact
bundle, and wasn't fully reliable even at native resolution).

Writes:
  game/assets/decor/<slug>/<n>.png   -- tightly cropped RGBA object sprites
  game/js/decor_manifest.js          -- {slug: [{file, w, h, area}, ...]}
"""
import numpy as np
from PIL import Image
from scipy import ndimage
import os, json

SRC_DIR = "/home/user/game/game/assets/locations_alpha"
OUT_DIR = "/home/user/game/game/assets/decor"
MANIFEST_PATH = "/home/user/game/game/js/decor_manifest.js"

os.makedirs(OUT_DIR, exist_ok=True)
manifest = {}

files = sorted(f for f in os.listdir(SRC_DIR) if f.endswith(".png"))
for fname in files:
    slug = fname[:-4]
    im = Image.open(os.path.join(SRC_DIR, fname)).convert("RGBA")
    arr = np.array(im)
    alpha = arr[:, :, 3]
    mask = alpha > 20

    # opening first: kills thin stray bridges/noise left over from checker
    # removal so unrelated neighboring objects don't get fused together
    opened = ndimage.binary_opening(mask, structure=np.ones((3, 3)), iterations=1)
    # then a small dilation to merge a single object's disjoint parts
    # (a tree's leaves/trunk can be separate components) before labeling
    dilated = ndimage.binary_dilation(opened, iterations=2)
    labeled, n = ndimage.label(dilated, structure=np.ones((3, 3)))

    objs = ndimage.find_objects(labeled)
    entries = []
    out_slug_dir = os.path.join(OUT_DIR, slug)
    os.makedirs(out_slug_dir, exist_ok=True)
    idx = 0
    total_area = mask.sum()
    for i, sl in enumerate(objs):
        if sl is None:
            continue
        ys, xs = sl
        comp_mask = (labeled[sl] == (i + 1)) & mask[sl]
        area = comp_mask.sum()
        if area < max(600, total_area * 0.004):
            continue  # skip tiny noise / icon fragments
        h = ys.stop - ys.start
        w = xs.stop - xs.start
        if h < 20 or w < 20:
            continue
        pad = 3
        y0, y1 = max(0, ys.start - pad), min(arr.shape[0], ys.stop + pad)
        x0, x1 = max(0, xs.start - pad), min(arr.shape[1], xs.stop + pad)
        crop = arr[y0:y1, x0:x1]
        # zero out alpha of any *other* component's pixels that leaked into this bbox
        crop_labels = labeled[y0:y1, x0:x1]
        keep = (crop_labels == (i + 1))
        crop = crop.copy()
        crop[~keep, 3] = 0
        out_path = os.path.join(out_slug_dir, f"{idx}.png")
        Image.fromarray(crop, "RGBA").save(out_path, optimize=True)
        entries.append({
            "file": f"assets/decor/{slug}/{idx}.png",
            "w": int(x1 - x0), "h": int(y1 - y0), "area": int(area),
        })
        idx += 1

    entries.sort(key=lambda e: -e["area"])
    manifest[slug] = entries[:14]
    print(f"{slug}: {len(entries)} objects kept")

with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by tools/slice_decor.py -- do not hand-edit.\n")
    f.write("const DECOR_MANIFEST = " + json.dumps(manifest, ensure_ascii=False, indent=1) + ";\n")

print("done, manifest ->", MANIFEST_PATH)
