// Auto-generated by tools/slice_decor.py -- do not hand-edit.
const DECOR_MANIFEST = {
 "altai": [
  {
   "file": "assets/decor/altai/0.png",
   "w": 236,
   "h": 563,
   "area": 59075
  },
  {
   "file": "assets/decor/altai/1.png",
   "w": 235,
   "h": 537,
   "area": 57494
  },
  {
   "file": "assets/decor/altai/9.png",
   "w": 410,
   "h": 196,
   "area": 47395
  },
  {
   "file": "assets/decor/altai/3.png",
   "w": 237,
   "h": 470,
   "area": 45582
  },
  {
   "file": "assets/decor/altai/8.png",
   "w": 286,
   "h": 209,
   "area": 30441
  },
  {
   "file": "assets/decor/altai/2.png",
   "w": 228,
   "h": 215,
   "area": 27130
  },
  {
   "file": "assets/decor/altai/12.png",
   "w": 288,
   "h": 123,
   "area": 22780
  },
  {
   "file": "assets/decor/altai/5.png",
   "w": 236,
   "h": 164,
   "area": 17538
  },
  {
   "file": "assets/decor/altai/15.png",
   "w": 243,
   "h": 108,
   "area": 16195
  },
  {
   "file": "assets/decor/altai/14.png",
   "w": 170,
   "h": 114,
   "area": 11778
  },
  {
   "file": "assets/decor/altai/13.png",
   "w": 197,
   "h": 105,
   "area": 9256
  },
  {
   "file": "assets/decor/altai/10.png",
   "w": 145,
   "h": 91,
   "area": 7323
  },
  {
   "file": "assets/decor/altai/6.png",
   "w": 97,
   "h": 77,
   "area": 3316
  },
  {
   "file": "assets/decor/altai/7.png",
   "w": 84,
   "h": 72,
   "area": 2754
  }
 ],
 "anapa": [
  {
   "file": "assets/decor/anapa/4.png",
   "w": 415,
   "h": 197,
   "area": 34272
  },
  {
   "file": "assets/decor/anapa/1.png",
   "w": 293,
   "h": 287,
   "area": 30430
  },
  {
   "file": "assets/decor/anapa/6.png",
   "w": 262,
   "h": 159,
   "area": 27731
  },
  {
   "file": "assets/decor/anapa/2.png",
   "w": 246,
   "h": 284,
   "area": 24511
  },
  {
   "file": "assets/decor/anapa/12.png",
   "w": 347,
   "h": 131,
   "area": 24109
  },
  {
   "file": "assets/decor/anapa/5.png",
   "w": 205,
   "h": 154,
   "area": 21393
  },
  {
   "file": "assets/decor/anapa/3.png",
   "w": 205,
   "h": 147,
   "area": 20348
  },
  {
   "file": "assets/decor/anapa/11.png",
   "w": 228,
   "h": 132,
   "area": 18496
  },
  {
   "file": "assets/decor/anapa/0.png",
   "w": 91,
   "h": 298,
   "area": 14853
  },
  {
   "file": "assets/decor/anapa/9.png",
   "w": 227,
   "h": 147,
   "area": 12152
  },
  {
   "file": "assets/decor/anapa/8.png",
   "w": 309,
   "h": 75,
   "area": 10472
  },
  {
   "file": "assets/decor/anapa/7.png",
   "w": 90,
   "h": 156,
   "area": 7304
  },
  {
   "file": "assets/decor/anapa/13.png",
   "w": 205,
   "h": 87,
   "area": 5831
  },
  {
   "file": "assets/decor/anapa/16.png",
   "w": 119,
   "h": 59,
   "area": 2498
  }
 ],
 "astrakhan": [
  {
   "file": "assets/decor/astrakhan/1.png",
   "w": 344,
   "h": 370,
   "area": 80518
  },
  {
   "file": "assets/decor/astrakhan/2.png",
   "w": 312,
   "h": 374,
   "area": 75127
  },
  {
   "file": "assets/decor/astrakhan/0.png",
   "w": 220,
   "h": 464,
   "area": 58057
  },
  {
   "file": "assets/decor/astrakhan/9.png",
   "w": 202,
   "h": 256,
   "area": 36180
  },
  {
   "file": "assets/decor/astrakhan/6.png",
   "w": 303,
   "h": 158,
   "area": 31241
  },
  {
   "file": "assets/decor/astrakhan/3.png",
   "w": 216,
   "h": 244,
   "area": 28693
  },
  {
   "file": "assets/decor/astrakhan/12.png",
   "w": 320,
   "h": 120,
   "area": 23827
  },
  {
   "file": "assets/decor/astrakhan/10.png",
   "w": 312,
   "h": 132,
   "area": 19649
  },
  {
   "file": "assets/decor/astrakhan/5.png",
   "w": 162,
   "h": 238,
   "area": 19427
  },
  {
   "file": "assets/decor/astrakhan/4.png",
   "w": 229,
   "h": 166,
   "area": 17877
  },
  {
   "file": "assets/decor/astrakhan/11.png",
   "w": 164,
   "h": 113,
   "area": 13449
  },
  {
   "file": "assets/decor/astrakhan/7.png",
   "w": 146,
   "h": 94,
   "area": 8345
  },
  {
   "file": "assets/decor/astrakhan/8.png",
   "w": 93,
   "h": 64,
   "area": 3272
  },
  {
   "file": "assets/decor/astrakhan/13.png",
   "w": 73,
   "h": 94,
   "area": 2041
  }
 ],
 "bali": [
  {
   "file": "assets/decor/bali/4.png",
   "w": 222,
   "h": 285,
   "area": 34416
  },
  {
   "file": "assets/decor/bali/9.png",
   "w": 375,
   "h": 117,
   "area": 33645
  },
  {
   "file": "assets/decor/bali/13.png",
   "w": 258,
   "h": 156,
   "area": 25647
  },
  {
   "file": "assets/decor/bali/3.png",
   "w": 251,
   "h": 300,
   "area": 24995
  },
  {
   "file": "assets/decor/bali/6.png",
   "w": 156,
   "h": 277,
   "area": 23718
  },
  {
   "file": "assets/decor/bali/12.png",
   "w": 249,
   "h": 158,
   "area": 23207
  },
  {
   "file": "assets/decor/bali/2.png",
   "w": 218,
   "h": 328,
   "area": 22790
  },
  {
   "file": "assets/decor/bali/5.png",
   "w": 139,
   "h": 277,
   "area": 22139
  },
  {
   "file": "assets/decor/bali/7.png",
   "w": 208,
   "h": 185,
   "area": 22032
  },
  {
   "file": "assets/decor/bali/1.png",
   "w": 192,
   "h": 339,
   "area": 21187
  },
  {
   "file": "assets/decor/bali/0.png",
   "w": 187,
   "h": 341,
   "area": 20008
  },
  {
   "file": "assets/decor/bali/10.png",
   "w": 185,
   "h": 116,
   "area": 13675
  },
  {
   "file": "assets/decor/bali/11.png",
   "w": 177,
   "h": 106,
   "area": 11159
  },
  {
   "file": "assets/decor/bali/14.png",
   "w": 144,
   "h": 120,
   "area": 10288
  }
 ],
 "belarus": [
  {
   "file": "assets/decor/belarus/1.png",
   "w": 228,
   "h": 319,
   "area": 55474
  },
  {
   "file": "assets/decor/belarus/6.png",
   "w": 185,
   "h": 221,
   "area": 29252
  },
  {
   "file": "assets/decor/belarus/0.png",
   "w": 194,
   "h": 334,
   "area": 26082
  },
  {
   "file": "assets/decor/belarus/2.png",
   "w": 149,
   "h": 321,
   "area": 23633
  },
  {
   "file": "assets/decor/belarus/4.png",
   "w": 180,
   "h": 316,
   "area": 23489
  },
  {
   "file": "assets/decor/belarus/3.png",
   "w": 155,
   "h": 318,
   "area": 21528
  },
  {
   "file": "assets/decor/belarus/10.png",
   "w": 251,
   "h": 116,
   "area": 17478
  },
  {
   "file": "assets/decor/belarus/5.png",
   "w": 150,
   "h": 389,
   "area": 15895
  },
  {
   "file": "assets/decor/belarus/12.png",
   "w": 239,
   "h": 106,
   "area": 15408
  },
  {
   "file": "assets/decor/belarus/11.png",
   "w": 239,
   "h": 110,
   "area": 13185
  },
  {
   "file": "assets/decor/belarus/8.png",
   "w": 162,
   "h": 96,
   "area": 9691
  },
  {
   "file": "assets/decor/belarus/7.png",
   "w": 170,
   "h": 136,
   "area": 7356
  },
  {
   "file": "assets/decor/belarus/17.png",
   "w": 118,
   "h": 80,
   "area": 5126
  },
  {
   "file": "assets/decor/belarus/14.png",
   "w": 317,
   "h": 106,
   "area": 4752
  }
 ],
 "belgorod": [
  {
   "file": "assets/decor/belgorod/4.png",
   "w": 462,
   "h": 248,
   "area": 46634
  },
  {
   "file": "assets/decor/belgorod/3.png",
   "w": 248,
   "h": 304,
   "area": 39543
  },
  {
   "file": "assets/decor/belgorod/2.png",
   "w": 248,
   "h": 305,
   "area": 39462
  },
  {
   "file": "assets/decor/belgorod/11.png",
   "w": 253,
   "h": 130,
   "area": 21495
  },
  {
   "file": "assets/decor/belgorod/8.png",
   "w": 201,
   "h": 174,
   "area": 20804
  },
  {
   "file": "assets/decor/belgorod/0.png",
   "w": 149,
   "h": 313,
   "area": 20008
  },
  {
   "file": "assets/decor/belgorod/1.png",
   "w": 153,
   "h": 309,
   "area": 19700
  },
  {
   "file": "assets/decor/belgorod/12.png",
   "w": 262,
   "h": 111,
   "area": 19694
  },
  {
   "file": "assets/decor/belgorod/9.png",
   "w": 190,
   "h": 134,
   "area": 13736
  },
  {
   "file": "assets/decor/belgorod/5.png",
   "w": 118,
   "h": 238,
   "area": 12013
  },
  {
   "file": "assets/decor/belgorod/7.png",
   "w": 82,
   "h": 195,
   "area": 7918
  },
  {
   "file": "assets/decor/belgorod/10.png",
   "w": 131,
   "h": 92,
   "area": 5461
  },
  {
   "file": "assets/decor/belgorod/6.png",
   "w": 140,
   "h": 163,
   "area": 3018
  },
  {
   "file": "assets/decor/belgorod/13.png",
   "w": 63,
   "h": 121,
   "area": 2525
  }
 ],
 "belgrade": [
  {
   "file": "assets/decor/belgrade/2.png",
   "w": 223,
   "h": 288,
   "area": 34594
  },
  {
   "file": "assets/decor/belgrade/4.png",
   "w": 198,
   "h": 251,
   "area": 31599
  },
  {
   "file": "assets/decor/belgrade/0.png",
   "w": 175,
   "h": 386,
   "area": 26974
  },
  {
   "file": "assets/decor/belgrade/7.png",
   "w": 318,
   "h": 165,
   "area": 26775
  },
  {
   "file": "assets/decor/belgrade/3.png",
   "w": 193,
   "h": 267,
   "area": 25652
  },
  {
   "file": "assets/decor/belgrade/10.png",
   "w": 172,
   "h": 223,
   "area": 19472
  },
  {
   "file": "assets/decor/belgrade/1.png",
   "w": 93,
   "h": 361,
   "area": 17501
  },
  {
   "file": "assets/decor/belgrade/11.png",
   "w": 156,
   "h": 192,
   "area": 12542
  },
  {
   "file": "assets/decor/belgrade/8.png",
   "w": 149,
   "h": 128,
   "area": 11257
  },
  {
   "file": "assets/decor/belgrade/9.png",
   "w": 113,
   "h": 85,
   "area": 4540
  },
  {
   "file": "assets/decor/belgrade/6.png",
   "w": 62,
   "h": 208,
   "area": 3968
  },
  {
   "file": "assets/decor/belgrade/12.png",
   "w": 96,
   "h": 61,
   "area": 1841
  },
  {
   "file": "assets/decor/belgrade/5.png",
   "w": 72,
   "h": 40,
   "area": 1362
  }
 ],
 "bulgaria": [
  {
   "file": "assets/decor/bulgaria/0.png",
   "w": 247,
   "h": 354,
   "area": 44906
  },
  {
   "file": "assets/decor/bulgaria/5.png",
   "w": 346,
   "h": 310,
   "area": 44507
  },
  {
   "file": "assets/decor/bulgaria/3.png",
   "w": 278,
   "h": 247,
   "area": 39919
  },
  {
   "file": "assets/decor/bulgaria/7.png",
   "w": 274,
   "h": 243,
   "area": 39895
  },
  {
   "file": "assets/decor/bulgaria/2.png",
   "w": 224,
   "h": 343,
   "area": 36860
  },
  {
   "file": "assets/decor/bulgaria/8.png",
   "w": 313,
   "h": 151,
   "area": 28158
  },
  {
   "file": "assets/decor/bulgaria/6.png",
   "w": 254,
   "h": 282,
   "area": 22893
  },
  {
   "file": "assets/decor/bulgaria/1.png",
   "w": 105,
   "h": 354,
   "area": 21037
  },
  {
   "file": "assets/decor/bulgaria/10.png",
   "w": 254,
   "h": 132,
   "area": 19493
  },
  {
   "file": "assets/decor/bulgaria/4.png",
   "w": 235,
   "h": 141,
   "area": 11140
  },
  {
   "file": "assets/decor/bulgaria/9.png",
   "w": 161,
   "h": 139,
   "area": 9748
  },
  {
   "file": "assets/decor/bulgaria/11.png",
   "w": 80,
   "h": 59,
   "area": 2350
  }
 ],
 "changan": [
  {
   "file": "assets/decor/changan/0.png",
   "w": 925,
   "h": 349,
   "area": 252133
  }
 ],
 "china": [
  {
   "file": "assets/decor/china/3.png",
   "w": 288,
   "h": 472,
   "area": 58087
  },
  {
   "file": "assets/decor/china/6.png",
   "w": 329,
   "h": 237,
   "area": 37208
  },
  {
   "file": "assets/decor/china/2.png",
   "w": 317,
   "h": 308,
   "area": 35488
  },
  {
   "file": "assets/decor/china/0.png",
   "w": 166,
   "h": 395,
   "area": 28593
  },
  {
   "file": "assets/decor/china/1.png",
   "w": 170,
   "h": 395,
   "area": 24981
  },
  {
   "file": "assets/decor/china/4.png",
   "w": 143,
   "h": 273,
   "area": 18378
  },
  {
   "file": "assets/decor/china/12.png",
   "w": 306,
   "h": 129,
   "area": 18142
  },
  {
   "file": "assets/decor/china/11.png",
   "w": 212,
   "h": 183,
   "area": 16493
  },
  {
   "file": "assets/decor/china/5.png",
   "w": 149,
   "h": 221,
   "area": 15089
  },
  {
   "file": "assets/decor/china/10.png",
   "w": 260,
   "h": 100,
   "area": 11686
  },
  {
   "file": "assets/decor/china/13.png",
   "w": 221,
   "h": 97,
   "area": 8689
  },
  {
   "file": "assets/decor/china/8.png",
   "w": 95,
   "h": 157,
   "area": 7347
  },
  {
   "file": "assets/decor/china/9.png",
   "w": 182,
   "h": 121,
   "area": 6825
  },
  {
   "file": "assets/decor/china/7.png",
   "w": 121,
   "h": 48,
   "area": 1281
  }
 ],
 "cuba": [
  {
   "file": "assets/decor/cuba/6.png",
   "w": 477,
   "h": 160,
   "area": 44247
  },
  {
   "file": "assets/decor/cuba/0.png",
   "w": 171,
   "h": 359,
   "area": 42998
  },
  {
   "file": "assets/decor/cuba/11.png",
   "w": 212,
   "h": 182,
   "area": 21277
  },
  {
   "file": "assets/decor/cuba/1.png",
   "w": 185,
   "h": 357,
   "area": 21136
  },
  {
   "file": "assets/decor/cuba/9.png",
   "w": 237,
   "h": 180,
   "area": 20940
  },
  {
   "file": "assets/decor/cuba/12.png",
   "w": 184,
   "h": 191,
   "area": 20829
  },
  {
   "file": "assets/decor/cuba/2.png",
   "w": 185,
   "h": 339,
   "area": 18574
  },
  {
   "file": "assets/decor/cuba/4.png",
   "w": 208,
   "h": 283,
   "area": 18491
  },
  {
   "file": "assets/decor/cuba/10.png",
   "w": 243,
   "h": 133,
   "area": 15159
  },
  {
   "file": "assets/decor/cuba/8.png",
   "w": 225,
   "h": 163,
   "area": 14671
  },
  {
   "file": "assets/decor/cuba/7.png",
   "w": 190,
   "h": 205,
   "area": 14457
  },
  {
   "file": "assets/decor/cuba/3.png",
   "w": 163,
   "h": 337,
   "area": 14396
  },
  {
   "file": "assets/decor/cuba/16.png",
   "w": 134,
   "h": 93,
   "area": 6956
  },
  {
   "file": "assets/decor/cuba/15.png",
   "w": 52,
   "h": 93,
   "area": 3506
  }
 ],
 "dagestan": [
  {
   "file": "assets/decor/dagestan/7.png",
   "w": 388,
   "h": 201,
   "area": 49513
  },
  {
   "file": "assets/decor/dagestan/6.png",
   "w": 303,
   "h": 200,
   "area": 43871
  },
  {
   "file": "assets/decor/dagestan/8.png",
   "w": 389,
   "h": 145,
   "area": 36872
  },
  {
   "file": "assets/decor/dagestan/9.png",
   "w": 389,
   "h": 141,
   "area": 34801
  },
  {
   "file": "assets/decor/dagestan/3.png",
   "w": 262,
   "h": 157,
   "area": 26252
  },
  {
   "file": "assets/decor/dagestan/4.png",
   "w": 249,
   "h": 147,
   "area": 25148
  },
  {
   "file": "assets/decor/dagestan/1.png",
   "w": 228,
   "h": 237,
   "area": 24832
  },
  {
   "file": "assets/decor/dagestan/0.png",
   "w": 212,
   "h": 239,
   "area": 23899
  },
  {
   "file": "assets/decor/dagestan/2.png",
   "w": 348,
   "h": 117,
   "area": 22468
  },
  {
   "file": "assets/decor/dagestan/5.png",
   "w": 83,
   "h": 256,
   "area": 13748
  },
  {
   "file": "assets/decor/dagestan/12.png",
   "w": 108,
   "h": 118,
   "area": 5384
  },
  {
   "file": "assets/decor/dagestan/14.png",
   "w": 75,
   "h": 55,
   "area": 1788
  },
  {
   "file": "assets/decor/dagestan/15.png",
   "w": 83,
   "h": 44,
   "area": 1559
  },
  {
   "file": "assets/decor/dagestan/10.png",
   "w": 41,
   "h": 128,
   "area": 1405
  }
 ],
 "drumnbass": [
  {
   "file": "assets/decor/drumnbass/0.png",
   "w": 623,
   "h": 657,
   "area": 315095
  },
  {
   "file": "assets/decor/drumnbass/2.png",
   "w": 317,
   "h": 327,
   "area": 54254
  },
  {
   "file": "assets/decor/drumnbass/1.png",
   "w": 227,
   "h": 263,
   "area": 34269
  },
  {
   "file": "assets/decor/drumnbass/3.png",
   "w": 285,
   "h": 185,
   "area": 28936
  },
  {
   "file": "assets/decor/drumnbass/8.png",
   "w": 338,
   "h": 119,
   "area": 22664
  },
  {
   "file": "assets/decor/drumnbass/10.png",
   "w": 330,
   "h": 103,
   "area": 19093
  },
  {
   "file": "assets/decor/drumnbass/4.png",
   "w": 154,
   "h": 152,
   "area": 15371
  },
  {
   "file": "assets/decor/drumnbass/5.png",
   "w": 45,
   "h": 232,
   "area": 3618
  },
  {
   "file": "assets/decor/drumnbass/6.png",
   "w": 64,
   "h": 220,
   "area": 3255
  },
  {
   "file": "assets/decor/drumnbass/7.png",
   "w": 64,
   "h": 219,
   "area": 3236
  },
  {
   "file": "assets/decor/drumnbass/9.png",
   "w": 79,
   "h": 62,
   "area": 2175
  }
 ],
 "dubai": [
  {
   "file": "assets/decor/dubai/9.png",
   "w": 482,
   "h": 143,
   "area": 49983
  },
  {
   "file": "assets/decor/dubai/8.png",
   "w": 192,
   "h": 224,
   "area": 30272
  },
  {
   "file": "assets/decor/dubai/11.png",
   "w": 271,
   "h": 167,
   "area": 26345
  },
  {
   "file": "assets/decor/dubai/1.png",
   "w": 248,
   "h": 338,
   "area": 23757
  },
  {
   "file": "assets/decor/dubai/10.png",
   "w": 328,
   "h": 201,
   "area": 21309
  },
  {
   "file": "assets/decor/dubai/7.png",
   "w": 139,
   "h": 247,
   "area": 16436
  },
  {
   "file": "assets/decor/dubai/2.png",
   "w": 177,
   "h": 349,
   "area": 13520
  },
  {
   "file": "assets/decor/dubai/13.png",
   "w": 416,
   "h": 94,
   "area": 13349
  },
  {
   "file": "assets/decor/dubai/0.png",
   "w": 216,
   "h": 337,
   "area": 13325
  },
  {
   "file": "assets/decor/dubai/12.png",
   "w": 220,
   "h": 117,
   "area": 13180
  },
  {
   "file": "assets/decor/dubai/6.png",
   "w": 75,
   "h": 69,
   "area": 1845
  },
  {
   "file": "assets/decor/dubai/3.png",
   "w": 86,
   "h": 68,
   "area": 1612
  },
  {
   "file": "assets/decor/dubai/5.png",
   "w": 53,
   "h": 72,
   "area": 1262
  },
  {
   "file": "assets/decor/dubai/4.png",
   "w": 55,
   "h": 69,
   "area": 1175
  }
 ],
 "georgia": [
  {
   "file": "assets/decor/georgia/4.png",
   "w": 378,
   "h": 214,
   "area": 50855
  },
  {
   "file": "assets/decor/georgia/2.png",
   "w": 279,
   "h": 225,
   "area": 33295
  },
  {
   "file": "assets/decor/georgia/6.png",
   "w": 260,
   "h": 173,
   "area": 27536
  },
  {
   "file": "assets/decor/georgia/1.png",
   "w": 188,
   "h": 240,
   "area": 20588
  },
  {
   "file": "assets/decor/georgia/0.png",
   "w": 145,
   "h": 254,
   "area": 17964
  },
  {
   "file": "assets/decor/georgia/8.png",
   "w": 197,
   "h": 148,
   "area": 17192
  },
  {
   "file": "assets/decor/georgia/7.png",
   "w": 211,
   "h": 292,
   "area": 14819
  },
  {
   "file": "assets/decor/georgia/9.png",
   "w": 198,
   "h": 122,
   "area": 12538
  },
  {
   "file": "assets/decor/georgia/15.png",
   "w": 273,
   "h": 86,
   "area": 12017
  },
  {
   "file": "assets/decor/georgia/14.png",
   "w": 261,
   "h": 89,
   "area": 11861
  },
  {
   "file": "assets/decor/georgia/10.png",
   "w": 211,
   "h": 130,
   "area": 10824
  },
  {
   "file": "assets/decor/georgia/5.png",
   "w": 192,
   "h": 215,
   "area": 10768
  },
  {
   "file": "assets/decor/georgia/3.png",
   "w": 165,
   "h": 227,
   "area": 7643
  },
  {
   "file": "assets/decor/georgia/11.png",
   "w": 150,
   "h": 111,
   "area": 6345
  }
 ],
 "goa": [
  {
   "file": "assets/decor/goa/5.png",
   "w": 381,
   "h": 222,
   "area": 54588
  },
  {
   "file": "assets/decor/goa/2.png",
   "w": 220,
   "h": 330,
   "area": 52940
  },
  {
   "file": "assets/decor/goa/10.png",
   "w": 274,
   "h": 237,
   "area": 50425
  },
  {
   "file": "assets/decor/goa/9.png",
   "w": 398,
   "h": 155,
   "area": 44265
  },
  {
   "file": "assets/decor/goa/0.png",
   "w": 263,
   "h": 413,
   "area": 34329
  },
  {
   "file": "assets/decor/goa/4.png",
   "w": 229,
   "h": 231,
   "area": 32709
  },
  {
   "file": "assets/decor/goa/1.png",
   "w": 251,
   "h": 406,
   "area": 32322
  },
  {
   "file": "assets/decor/goa/6.png",
   "w": 285,
   "h": 278,
   "area": 25116
  },
  {
   "file": "assets/decor/goa/3.png",
   "w": 213,
   "h": 259,
   "area": 21594
  },
  {
   "file": "assets/decor/goa/13.png",
   "w": 253,
   "h": 103,
   "area": 16002
  },
  {
   "file": "assets/decor/goa/8.png",
   "w": 247,
   "h": 95,
   "area": 13383
  },
  {
   "file": "assets/decor/goa/12.png",
   "w": 113,
   "h": 95,
   "area": 7657
  },
  {
   "file": "assets/decor/goa/11.png",
   "w": 98,
   "h": 102,
   "area": 4647
  },
  {
   "file": "assets/decor/goa/14.png",
   "w": 135,
   "h": 62,
   "area": 3947
  }
 ],
 "hungary": [
  {
   "file": "assets/decor/hungary/5.png",
   "w": 291,
   "h": 243,
   "area": 56526
  },
  {
   "file": "assets/decor/hungary/0.png",
   "w": 135,
   "h": 356,
   "area": 28103
  },
  {
   "file": "assets/decor/hungary/6.png",
   "w": 231,
   "h": 176,
   "area": 25812
  },
  {
   "file": "assets/decor/hungary/1.png",
   "w": 127,
   "h": 341,
   "area": 25711
  },
  {
   "file": "assets/decor/hungary/2.png",
   "w": 338,
   "h": 323,
   "area": 18000
  },
  {
   "file": "assets/decor/hungary/11.png",
   "w": 229,
   "h": 121,
   "area": 17887
  },
  {
   "file": "assets/decor/hungary/12.png",
   "w": 224,
   "h": 111,
   "area": 17047
  },
  {
   "file": "assets/decor/hungary/10.png",
   "w": 199,
   "h": 153,
   "area": 16001
  },
  {
   "file": "assets/decor/hungary/3.png",
   "w": 96,
   "h": 249,
   "area": 11223
  },
  {
   "file": "assets/decor/hungary/4.png",
   "w": 95,
   "h": 206,
   "area": 8805
  },
  {
   "file": "assets/decor/hungary/8.png",
   "w": 181,
   "h": 132,
   "area": 8235
  },
  {
   "file": "assets/decor/hungary/7.png",
   "w": 163,
   "h": 174,
   "area": 8055
  },
  {
   "file": "assets/decor/hungary/9.png",
   "w": 178,
   "h": 163,
   "area": 7798
  },
  {
   "file": "assets/decor/hungary/14.png",
   "w": 91,
   "h": 85,
   "area": 4347
  }
 ],
 "hurghada": [
  {
   "file": "assets/decor/hurghada/0.png",
   "w": 246,
   "h": 325,
   "area": 31287
  },
  {
   "file": "assets/decor/hurghada/2.png",
   "w": 259,
   "h": 296,
   "area": 30946
  },
  {
   "file": "assets/decor/hurghada/3.png",
   "w": 279,
   "h": 161,
   "area": 28990
  },
  {
   "file": "assets/decor/hurghada/1.png",
   "w": 253,
   "h": 300,
   "area": 27833
  },
  {
   "file": "assets/decor/hurghada/4.png",
   "w": 272,
   "h": 151,
   "area": 24746
  },
  {
   "file": "assets/decor/hurghada/13.png",
   "w": 248,
   "h": 183,
   "area": 22816
  },
  {
   "file": "assets/decor/hurghada/9.png",
   "w": 253,
   "h": 116,
   "area": 20052
  },
  {
   "file": "assets/decor/hurghada/7.png",
   "w": 194,
   "h": 217,
   "area": 17582
  },
  {
   "file": "assets/decor/hurghada/8.png",
   "w": 183,
   "h": 166,
   "area": 17177
  },
  {
   "file": "assets/decor/hurghada/11.png",
   "w": 197,
   "h": 188,
   "area": 15836
  },
  {
   "file": "assets/decor/hurghada/6.png",
   "w": 256,
   "h": 118,
   "area": 14830
  },
  {
   "file": "assets/decor/hurghada/10.png",
   "w": 232,
   "h": 101,
   "area": 13019
  },
  {
   "file": "assets/decor/hurghada/5.png",
   "w": 197,
   "h": 137,
   "area": 7633
  },
  {
   "file": "assets/decor/hurghada/12.png",
   "w": 80,
   "h": 46,
   "area": 1546
  }
 ],
 "istanbul": [
  {
   "file": "assets/decor/istanbul/3.png",
   "w": 216,
   "h": 408,
   "area": 68372
  },
  {
   "file": "assets/decor/istanbul/4.png",
   "w": 360,
   "h": 405,
   "area": 41927
  },
  {
   "file": "assets/decor/istanbul/9.png",
   "w": 371,
   "h": 172,
   "area": 33317
  },
  {
   "file": "assets/decor/istanbul/8.png",
   "w": 195,
   "h": 167,
   "area": 27251
  },
  {
   "file": "assets/decor/istanbul/7.png",
   "w": 241,
   "h": 185,
   "area": 26775
  },
  {
   "file": "assets/decor/istanbul/1.png",
   "w": 106,
   "h": 430,
   "area": 25123
  },
  {
   "file": "assets/decor/istanbul/10.png",
   "w": 316,
   "h": 166,
   "area": 24981
  },
  {
   "file": "assets/decor/istanbul/2.png",
   "w": 108,
   "h": 428,
   "area": 23776
  },
  {
   "file": "assets/decor/istanbul/0.png",
   "w": 108,
   "h": 440,
   "area": 23748
  },
  {
   "file": "assets/decor/istanbul/13.png",
   "w": 301,
   "h": 160,
   "area": 22697
  },
  {
   "file": "assets/decor/istanbul/6.png",
   "w": 130,
   "h": 461,
   "area": 15953
  },
  {
   "file": "assets/decor/istanbul/11.png",
   "w": 213,
   "h": 149,
   "area": 15678
  },
  {
   "file": "assets/decor/istanbul/5.png",
   "w": 244,
   "h": 47,
   "area": 2833
  },
  {
   "file": "assets/decor/istanbul/12.png",
   "w": 49,
   "h": 112,
   "area": 2296
  }
 ],
 "italy": [
  {
   "file": "assets/decor/italy/5.png",
   "w": 328,
   "h": 178,
   "area": 50020
  },
  {
   "file": "assets/decor/italy/2.png",
   "w": 323,
   "h": 279,
   "area": 30877
  },
  {
   "file": "assets/decor/italy/10.png",
   "w": 273,
   "h": 152,
   "area": 26975
  },
  {
   "file": "assets/decor/italy/7.png",
   "w": 246,
   "h": 154,
   "area": 23224
  },
  {
   "file": "assets/decor/italy/11.png",
   "w": 256,
   "h": 119,
   "area": 16411
  },
  {
   "file": "assets/decor/italy/0.png",
   "w": 86,
   "h": 324,
   "area": 15355
  },
  {
   "file": "assets/decor/italy/6.png",
   "w": 153,
   "h": 170,
   "area": 15123
  },
  {
   "file": "assets/decor/italy/1.png",
   "w": 80,
   "h": 310,
   "area": 13543
  },
  {
   "file": "assets/decor/italy/4.png",
   "w": 181,
   "h": 193,
   "area": 12745
  },
  {
   "file": "assets/decor/italy/9.png",
   "w": 121,
   "h": 184,
   "area": 11816
  },
  {
   "file": "assets/decor/italy/8.png",
   "w": 148,
   "h": 111,
   "area": 10206
  },
  {
   "file": "assets/decor/italy/12.png",
   "w": 195,
   "h": 107,
   "area": 9023
  },
  {
   "file": "assets/decor/italy/15.png",
   "w": 126,
   "h": 114,
   "area": 7658
  },
  {
   "file": "assets/decor/italy/3.png",
   "w": 174,
   "h": 202,
   "area": 7534
  }
 ],
 "kaliningrad": [
  {
   "file": "assets/decor/kaliningrad/4.png",
   "w": 259,
   "h": 268,
   "area": 56401
  },
  {
   "file": "assets/decor/kaliningrad/1.png",
   "w": 210,
   "h": 318,
   "area": 35759
  },
  {
   "file": "assets/decor/kaliningrad/0.png",
   "w": 200,
   "h": 318,
   "area": 34569
  },
  {
   "file": "assets/decor/kaliningrad/2.png",
   "w": 212,
   "h": 312,
   "area": 32474
  },
  {
   "file": "assets/decor/kaliningrad/3.png",
   "w": 190,
   "h": 282,
   "area": 32124
  },
  {
   "file": "assets/decor/kaliningrad/5.png",
   "w": 222,
   "h": 142,
   "area": 15200
  },
  {
   "file": "assets/decor/kaliningrad/11.png",
   "w": 253,
   "h": 90,
   "area": 11629
  },
  {
   "file": "assets/decor/kaliningrad/6.png",
   "w": 231,
   "h": 107,
   "area": 11040
  },
  {
   "file": "assets/decor/kaliningrad/10.png",
   "w": 156,
   "h": 98,
   "area": 8781
  },
  {
   "file": "assets/decor/kaliningrad/9.png",
   "w": 154,
   "h": 110,
   "area": 7774
  },
  {
   "file": "assets/decor/kaliningrad/8.png",
   "w": 44,
   "h": 173,
   "area": 5399
  },
  {
   "file": "assets/decor/kaliningrad/7.png",
   "w": 62,
   "h": 226,
   "area": 5152
  },
  {
   "file": "assets/decor/kaliningrad/12.png",
   "w": 134,
   "h": 61,
   "area": 2742
  }
 ],
 "kaliningrad_scooter": [
  {
   "file": "assets/decor/kaliningrad_scooter/0.png",
   "w": 692,
   "h": 712,
   "area": 133549
  }
 ],
 "kaluga": [
  {
   "file": "assets/decor/kaluga/5.png",
   "w": 287,
   "h": 300,
   "area": 56612
  },
  {
   "file": "assets/decor/kaluga/3.png",
   "w": 222,
   "h": 306,
   "area": 37418
  },
  {
   "file": "assets/decor/kaluga/2.png",
   "w": 223,
   "h": 306,
   "area": 36909
  },
  {
   "file": "assets/decor/kaluga/12.png",
   "w": 204,
   "h": 180,
   "area": 23709
  },
  {
   "file": "assets/decor/kaluga/1.png",
   "w": 149,
   "h": 304,
   "area": 21671
  },
  {
   "file": "assets/decor/kaluga/0.png",
   "w": 152,
   "h": 307,
   "area": 19874
  },
  {
   "file": "assets/decor/kaluga/11.png",
   "w": 157,
   "h": 178,
   "area": 12283
  },
  {
   "file": "assets/decor/kaluga/13.png",
   "w": 159,
   "h": 178,
   "area": 11123
  },
  {
   "file": "assets/decor/kaluga/9.png",
   "w": 222,
   "h": 165,
   "area": 9571
  },
  {
   "file": "assets/decor/kaluga/4.png",
   "w": 141,
   "h": 241,
   "area": 9354
  },
  {
   "file": "assets/decor/kaluga/10.png",
   "w": 172,
   "h": 149,
   "area": 7197
  },
  {
   "file": "assets/decor/kaluga/6.png",
   "w": 92,
   "h": 289,
   "area": 6589
  },
  {
   "file": "assets/decor/kaluga/7.png",
   "w": 55,
   "h": 209,
   "area": 4527
  },
  {
   "file": "assets/decor/kaluga/8.png",
   "w": 141,
   "h": 136,
   "area": 3738
  }
 ],
 "karelia": [
  {
   "file": "assets/decor/karelia/8.png",
   "w": 386,
   "h": 204,
   "area": 59025
  },
  {
   "file": "assets/decor/karelia/6.png",
   "w": 286,
   "h": 257,
   "area": 44465
  },
  {
   "file": "assets/decor/karelia/3.png",
   "w": 189,
   "h": 403,
   "area": 35981
  },
  {
   "file": "assets/decor/karelia/0.png",
   "w": 180,
   "h": 423,
   "area": 35878
  },
  {
   "file": "assets/decor/karelia/5.png",
   "w": 226,
   "h": 331,
   "area": 33427
  },
  {
   "file": "assets/decor/karelia/7.png",
   "w": 207,
   "h": 219,
   "area": 28673
  },
  {
   "file": "assets/decor/karelia/16.png",
   "w": 294,
   "h": 141,
   "area": 22388
  },
  {
   "file": "assets/decor/karelia/12.png",
   "w": 152,
   "h": 223,
   "area": 15807
  },
  {
   "file": "assets/decor/karelia/4.png",
   "w": 152,
   "h": 395,
   "area": 15652
  },
  {
   "file": "assets/decor/karelia/14.png",
   "w": 213,
   "h": 140,
   "area": 15226
  },
  {
   "file": "assets/decor/karelia/2.png",
   "w": 161,
   "h": 409,
   "area": 14867
  },
  {
   "file": "assets/decor/karelia/15.png",
   "w": 154,
   "h": 139,
   "area": 10802
  },
  {
   "file": "assets/decor/karelia/10.png",
   "w": 179,
   "h": 80,
   "area": 6872
  },
  {
   "file": "assets/decor/karelia/1.png",
   "w": 182,
   "h": 138,
   "area": 4441
  }
 ],
 "kasimov": [
  {
   "file": "assets/decor/kasimov/8.png",
   "w": 242,
   "h": 339,
   "area": 65108
  },
  {
   "file": "assets/decor/kasimov/5.png",
   "w": 289,
   "h": 308,
   "area": 62590
  },
  {
   "file": "assets/decor/kasimov/1.png",
   "w": 265,
   "h": 295,
   "area": 41085
  },
  {
   "file": "assets/decor/kasimov/2.png",
   "w": 266,
   "h": 295,
   "area": 41033
  },
  {
   "file": "assets/decor/kasimov/3.png",
   "w": 161,
   "h": 341,
   "area": 24720
  },
  {
   "file": "assets/decor/kasimov/0.png",
   "w": 172,
   "h": 346,
   "area": 24600
  },
  {
   "file": "assets/decor/kasimov/11.png",
   "w": 259,
   "h": 134,
   "area": 19175
  },
  {
   "file": "assets/decor/kasimov/10.png",
   "w": 208,
   "h": 171,
   "area": 17448
  },
  {
   "file": "assets/decor/kasimov/4.png",
   "w": 98,
   "h": 361,
   "area": 16965
  },
  {
   "file": "assets/decor/kasimov/6.png",
   "w": 167,
   "h": 147,
   "area": 15019
  },
  {
   "file": "assets/decor/kasimov/7.png",
   "w": 185,
   "h": 117,
   "area": 14125
  },
  {
   "file": "assets/decor/kasimov/9.png",
   "w": 126,
   "h": 226,
   "area": 11719
  }
 ],
 "kazakhstan": [
  {
   "file": "assets/decor/kazakhstan/0.png",
   "w": 236,
   "h": 225,
   "area": 46832
  },
  {
   "file": "assets/decor/kazakhstan/2.png",
   "w": 213,
   "h": 202,
   "area": 26720
  },
  {
   "file": "assets/decor/kazakhstan/5.png",
   "w": 321,
   "h": 136,
   "area": 24776
  },
  {
   "file": "assets/decor/kazakhstan/3.png",
   "w": 192,
   "h": 162,
   "area": 19199
  },
  {
   "file": "assets/decor/kazakhstan/6.png",
   "w": 251,
   "h": 113,
   "area": 15703
  },
  {
   "file": "assets/decor/kazakhstan/7.png",
   "w": 213,
   "h": 87,
   "area": 10418
  },
  {
   "file": "assets/decor/kazakhstan/1.png",
   "w": 198,
   "h": 101,
   "area": 7862
  },
  {
   "file": "assets/decor/kazakhstan/4.png",
   "w": 185,
   "h": 101,
   "area": 7552
  },
  {
   "file": "assets/decor/kazakhstan/10.png",
   "w": 128,
   "h": 140,
   "area": 6899
  },
  {
   "file": "assets/decor/kazakhstan/24.png",
   "w": 232,
   "h": 66,
   "area": 4634
  },
  {
   "file": "assets/decor/kazakhstan/9.png",
   "w": 90,
   "h": 138,
   "area": 2845
  },
  {
   "file": "assets/decor/kazakhstan/22.png",
   "w": 133,
   "h": 51,
   "area": 2569
  },
  {
   "file": "assets/decor/kazakhstan/17.png",
   "w": 84,
   "h": 85,
   "area": 2303
  },
  {
   "file": "assets/decor/kazakhstan/12.png",
   "w": 63,
   "h": 78,
   "area": 1861
  }
 ],
 "kazan": [
  {
   "file": "assets/decor/kazan/5.png",
   "w": 432,
   "h": 270,
   "area": 50550
  },
  {
   "file": "assets/decor/kazan/2.png",
   "w": 253,
   "h": 281,
   "area": 44723
  },
  {
   "file": "assets/decor/kazan/4.png",
   "w": 232,
   "h": 286,
   "area": 38856
  },
  {
   "file": "assets/decor/kazan/0.png",
   "w": 170,
   "h": 306,
   "area": 27014
  },
  {
   "file": "assets/decor/kazan/1.png",
   "w": 170,
   "h": 306,
   "area": 26997
  },
  {
   "file": "assets/decor/kazan/3.png",
   "w": 158,
   "h": 303,
   "area": 15793
  },
  {
   "file": "assets/decor/kazan/6.png",
   "w": 173,
   "h": 153,
   "area": 8016
  },
  {
   "file": "assets/decor/kazan/11.png",
   "w": 175,
   "h": 107,
   "area": 7126
  },
  {
   "file": "assets/decor/kazan/7.png",
   "w": 113,
   "h": 145,
   "area": 6992
  },
  {
   "file": "assets/decor/kazan/9.png",
   "w": 94,
   "h": 133,
   "area": 6331
  },
  {
   "file": "assets/decor/kazan/8.png",
   "w": 93,
   "h": 139,
   "area": 6125
  },
  {
   "file": "assets/decor/kazan/10.png",
   "w": 96,
   "h": 130,
   "area": 5569
  },
  {
   "file": "assets/decor/kazan/12.png",
   "w": 104,
   "h": 59,
   "area": 2564
  },
  {
   "file": "assets/decor/kazan/13.png",
   "w": 87,
   "h": 59,
   "area": 2333
  }
 ],
 "kirovsk": [
  {
   "file": "assets/decor/kirovsk/7.png",
   "w": 235,
   "h": 355,
   "area": 43005
  },
  {
   "file": "assets/decor/kirovsk/2.png",
   "w": 215,
   "h": 345,
   "area": 32810
  },
  {
   "file": "assets/decor/kirovsk/19.png",
   "w": 320,
   "h": 154,
   "area": 31721
  },
  {
   "file": "assets/decor/kirovsk/9.png",
   "w": 232,
   "h": 207,
   "area": 24014
  },
  {
   "file": "assets/decor/kirovsk/4.png",
   "w": 200,
   "h": 291,
   "area": 22924
  },
  {
   "file": "assets/decor/kirovsk/18.png",
   "w": 414,
   "h": 174,
   "area": 22461
  },
  {
   "file": "assets/decor/kirovsk/17.png",
   "w": 204,
   "h": 199,
   "area": 19475
  },
  {
   "file": "assets/decor/kirovsk/8.png",
   "w": 237,
   "h": 197,
   "area": 19249
  },
  {
   "file": "assets/decor/kirovsk/5.png",
   "w": 167,
   "h": 261,
   "area": 17398
  },
  {
   "file": "assets/decor/kirovsk/6.png",
   "w": 279,
   "h": 302,
   "area": 17125
  },
  {
   "file": "assets/decor/kirovsk/1.png",
   "w": 199,
   "h": 344,
   "area": 13631
  },
  {
   "file": "assets/decor/kirovsk/11.png",
   "w": 178,
   "h": 150,
   "area": 11405
  },
  {
   "file": "assets/decor/kirovsk/3.png",
   "w": 182,
   "h": 315,
   "area": 10260
  },
  {
   "file": "assets/decor/kirovsk/13.png",
   "w": 379,
   "h": 150,
   "area": 8980
  }
 ],
 "kirovsk_ambulance": [
  {
   "file": "assets/decor/kirovsk_ambulance/0.png",
   "w": 850,
   "h": 502,
   "area": 251855
  }
 ],
 "kolomna": [
  {
   "file": "assets/decor/kolomna/5.png",
   "w": 236,
   "h": 239,
   "area": 30341
  },
  {
   "file": "assets/decor/kolomna/6.png",
   "w": 176,
   "h": 183,
   "area": 26265
  },
  {
   "file": "assets/decor/kolomna/11.png",
   "w": 260,
   "h": 191,
   "area": 24533
  },
  {
   "file": "assets/decor/kolomna/3.png",
   "w": 180,
   "h": 221,
   "area": 21352
  },
  {
   "file": "assets/decor/kolomna/0.png",
   "w": 146,
   "h": 247,
   "area": 17963
  },
  {
   "file": "assets/decor/kolomna/1.png",
   "w": 133,
   "h": 228,
   "area": 15073
  },
  {
   "file": "assets/decor/kolomna/2.png",
   "w": 174,
   "h": 156,
   "area": 14935
  },
  {
   "file": "assets/decor/kolomna/12.png",
   "w": 190,
   "h": 144,
   "area": 12076
  },
  {
   "file": "assets/decor/kolomna/13.png",
   "w": 167,
   "h": 143,
   "area": 11741
  },
  {
   "file": "assets/decor/kolomna/14.png",
   "w": 130,
   "h": 123,
   "area": 8441
  },
  {
   "file": "assets/decor/kolomna/10.png",
   "w": 118,
   "h": 97,
   "area": 5649
  },
  {
   "file": "assets/decor/kolomna/7.png",
   "w": 71,
   "h": 147,
   "area": 4711
  },
  {
   "file": "assets/decor/kolomna/20.png",
   "w": 92,
   "h": 78,
   "area": 2748
  },
  {
   "file": "assets/decor/kolomna/15.png",
   "w": 75,
   "h": 82,
   "area": 2243
  }
 ],
 "korea": [
  {
   "file": "assets/decor/korea/2.png",
   "w": 243,
   "h": 287,
   "area": 45561
  },
  {
   "file": "assets/decor/korea/1.png",
   "w": 248,
   "h": 289,
   "area": 33869
  },
  {
   "file": "assets/decor/korea/4.png",
   "w": 271,
   "h": 268,
   "area": 30587
  },
  {
   "file": "assets/decor/korea/0.png",
   "w": 220,
   "h": 295,
   "area": 29399
  },
  {
   "file": "assets/decor/korea/3.png",
   "w": 249,
   "h": 277,
   "area": 28403
  },
  {
   "file": "assets/decor/korea/13.png",
   "w": 305,
   "h": 121,
   "area": 20717
  },
  {
   "file": "assets/decor/korea/10.png",
   "w": 289,
   "h": 91,
   "area": 15544
  },
  {
   "file": "assets/decor/korea/7.png",
   "w": 175,
   "h": 166,
   "area": 12819
  },
  {
   "file": "assets/decor/korea/5.png",
   "w": 108,
   "h": 191,
   "area": 8563
  },
  {
   "file": "assets/decor/korea/8.png",
   "w": 174,
   "h": 121,
   "area": 8272
  },
  {
   "file": "assets/decor/korea/6.png",
   "w": 111,
   "h": 182,
   "area": 6061
  },
  {
   "file": "assets/decor/korea/12.png",
   "w": 81,
   "h": 87,
   "area": 2771
  },
  {
   "file": "assets/decor/korea/9.png",
   "w": 92,
   "h": 75,
   "area": 2535
  },
  {
   "file": "assets/decor/korea/11.png",
   "w": 95,
   "h": 58,
   "area": 2358
  }
 ],
 "murom": [
  {
   "file": "assets/decor/murom/1.png",
   "w": 255,
   "h": 477,
   "area": 50043
  },
  {
   "file": "assets/decor/murom/0.png",
   "w": 218,
   "h": 482,
   "area": 40393
  },
  {
   "file": "assets/decor/murom/2.png",
   "w": 206,
   "h": 461,
   "area": 39799
  },
  {
   "file": "assets/decor/murom/3.png",
   "w": 189,
   "h": 461,
   "area": 37979
  },
  {
   "file": "assets/decor/murom/11.png",
   "w": 283,
   "h": 177,
   "area": 34089
  },
  {
   "file": "assets/decor/murom/4.png",
   "w": 223,
   "h": 250,
   "area": 25295
  },
  {
   "file": "assets/decor/murom/14.png",
   "w": 239,
   "h": 113,
   "area": 14180
  },
  {
   "file": "assets/decor/murom/5.png",
   "w": 123,
   "h": 227,
   "area": 12507
  },
  {
   "file": "assets/decor/murom/10.png",
   "w": 236,
   "h": 99,
   "area": 10294
  },
  {
   "file": "assets/decor/murom/9.png",
   "w": 207,
   "h": 105,
   "area": 10242
  },
  {
   "file": "assets/decor/murom/6.png",
   "w": 190,
   "h": 210,
   "area": 9474
  },
  {
   "file": "assets/decor/murom/8.png",
   "w": 164,
   "h": 106,
   "area": 7182
  },
  {
   "file": "assets/decor/murom/12.png",
   "w": 76,
   "h": 123,
   "area": 2909
  },
  {
   "file": "assets/decor/murom/13.png",
   "w": 71,
   "h": 115,
   "area": 2302
  }
 ],
 "newyear": [
  {
   "file": "assets/decor/newyear/1.png",
   "w": 393,
   "h": 443,
   "area": 108022
  },
  {
   "file": "assets/decor/newyear/4.png",
   "w": 469,
   "h": 362,
   "area": 105076
  },
  {
   "file": "assets/decor/newyear/0.png",
   "w": 314,
   "h": 445,
   "area": 71536
  },
  {
   "file": "assets/decor/newyear/8.png",
   "w": 571,
   "h": 147,
   "area": 40291
  },
  {
   "file": "assets/decor/newyear/2.png",
   "w": 269,
   "h": 166,
   "area": 28567
  },
  {
   "file": "assets/decor/newyear/3.png",
   "w": 230,
   "h": 190,
   "area": 27440
  },
  {
   "file": "assets/decor/newyear/5.png",
   "w": 213,
   "h": 201,
   "area": 25395
  },
  {
   "file": "assets/decor/newyear/6.png",
   "w": 131,
   "h": 139,
   "area": 12504
  },
  {
   "file": "assets/decor/newyear/7.png",
   "w": 443,
   "h": 104,
   "area": 10933
  }
 ],
 "orel": [
  {
   "file": "assets/decor/orel/5.png",
   "w": 373,
   "h": 262,
   "area": 70103
  },
  {
   "file": "assets/decor/orel/3.png",
   "w": 259,
   "h": 296,
   "area": 43728
  },
  {
   "file": "assets/decor/orel/2.png",
   "w": 260,
   "h": 297,
   "area": 43662
  },
  {
   "file": "assets/decor/orel/12.png",
   "w": 318,
   "h": 160,
   "area": 32668
  },
  {
   "file": "assets/decor/orel/6.png",
   "w": 247,
   "h": 157,
   "area": 28557
  },
  {
   "file": "assets/decor/orel/7.png",
   "w": 230,
   "h": 156,
   "area": 28128
  },
  {
   "file": "assets/decor/orel/0.png",
   "w": 175,
   "h": 308,
   "area": 26759
  },
  {
   "file": "assets/decor/orel/1.png",
   "w": 175,
   "h": 308,
   "area": 26708
  },
  {
   "file": "assets/decor/orel/4.png",
   "w": 162,
   "h": 258,
   "area": 19971
  },
  {
   "file": "assets/decor/orel/8.png",
   "w": 181,
   "h": 132,
   "area": 15706
  },
  {
   "file": "assets/decor/orel/13.png",
   "w": 176,
   "h": 131,
   "area": 11816
  },
  {
   "file": "assets/decor/orel/11.png",
   "w": 159,
   "h": 169,
   "area": 11482
  },
  {
   "file": "assets/decor/orel/9.png",
   "w": 175,
   "h": 112,
   "area": 10549
  },
  {
   "file": "assets/decor/orel/10.png",
   "w": 93,
   "h": 128,
   "area": 6843
  }
 ],
 "philippines": [
  {
   "file": "assets/decor/philippines/5.png",
   "w": 399,
   "h": 204,
   "area": 47607
  },
  {
   "file": "assets/decor/philippines/7.png",
   "w": 328,
   "h": 208,
   "area": 34193
  },
  {
   "file": "assets/decor/philippines/4.png",
   "w": 210,
   "h": 218,
   "area": 24157
  },
  {
   "file": "assets/decor/philippines/1.png",
   "w": 217,
   "h": 291,
   "area": 22549
  },
  {
   "file": "assets/decor/philippines/8.png",
   "w": 190,
   "h": 200,
   "area": 21721
  },
  {
   "file": "assets/decor/philippines/3.png",
   "w": 233,
   "h": 266,
   "area": 21475
  },
  {
   "file": "assets/decor/philippines/6.png",
   "w": 195,
   "h": 209,
   "area": 20511
  },
  {
   "file": "assets/decor/philippines/11.png",
   "w": 248,
   "h": 116,
   "area": 17536
  },
  {
   "file": "assets/decor/philippines/0.png",
   "w": 173,
   "h": 302,
   "area": 17449
  },
  {
   "file": "assets/decor/philippines/2.png",
   "w": 266,
   "h": 266,
   "area": 17408
  },
  {
   "file": "assets/decor/philippines/12.png",
   "w": 246,
   "h": 111,
   "area": 17164
  },
  {
   "file": "assets/decor/philippines/10.png",
   "w": 161,
   "h": 131,
   "area": 12022
  },
  {
   "file": "assets/decor/philippines/15.png",
   "w": 99,
   "h": 79,
   "area": 3786
  },
  {
   "file": "assets/decor/philippines/14.png",
   "w": 102,
   "h": 67,
   "area": 2764
  }
 ],
 "romania": [
  {
   "file": "assets/decor/romania/0.png",
   "w": 246,
   "h": 444,
   "area": 51068
  },
  {
   "file": "assets/decor/romania/2.png",
   "w": 217,
   "h": 433,
   "area": 41104
  },
  {
   "file": "assets/decor/romania/11.png",
   "w": 226,
   "h": 205,
   "area": 35836
  },
  {
   "file": "assets/decor/romania/1.png",
   "w": 169,
   "h": 440,
   "area": 29155
  },
  {
   "file": "assets/decor/romania/5.png",
   "w": 284,
   "h": 143,
   "area": 27583
  },
  {
   "file": "assets/decor/romania/3.png",
   "w": 269,
   "h": 416,
   "area": 24657
  },
  {
   "file": "assets/decor/romania/15.png",
   "w": 290,
   "h": 93,
   "area": 16648
  },
  {
   "file": "assets/decor/romania/4.png",
   "w": 185,
   "h": 192,
   "area": 16439
  },
  {
   "file": "assets/decor/romania/10.png",
   "w": 283,
   "h": 91,
   "area": 16151
  },
  {
   "file": "assets/decor/romania/6.png",
   "w": 207,
   "h": 138,
   "area": 5178
  },
  {
   "file": "assets/decor/romania/7.png",
   "w": 170,
   "h": 102,
   "area": 3570
  },
  {
   "file": "assets/decor/romania/8.png",
   "w": 110,
   "h": 92,
   "area": 2665
  },
  {
   "file": "assets/decor/romania/14.png",
   "w": 65,
   "h": 65,
   "area": 1919
  },
  {
   "file": "assets/decor/romania/9.png",
   "w": 98,
   "h": 55,
   "area": 1690
  }
 ],
 "scooter": [
  {
   "file": "assets/decor/scooter/0.png",
   "w": 646,
   "h": 502,
   "area": 159706
  }
 ],
 "signal": [
  {
   "file": "assets/decor/signal/2.png",
   "w": 393,
   "h": 320,
   "area": 41238
  },
  {
   "file": "assets/decor/signal/8.png",
   "w": 238,
   "h": 196,
   "area": 30383
  },
  {
   "file": "assets/decor/signal/7.png",
   "w": 274,
   "h": 202,
   "area": 26390
  },
  {
   "file": "assets/decor/signal/1.png",
   "w": 152,
   "h": 359,
   "area": 22127
  },
  {
   "file": "assets/decor/signal/9.png",
   "w": 330,
   "h": 128,
   "area": 21710
  },
  {
   "file": "assets/decor/signal/3.png",
   "w": 175,
   "h": 312,
   "area": 16754
  },
  {
   "file": "assets/decor/signal/5.png",
   "w": 120,
   "h": 226,
   "area": 12317
  },
  {
   "file": "assets/decor/signal/0.png",
   "w": 113,
   "h": 344,
   "area": 11525
  },
  {
   "file": "assets/decor/signal/4.png",
   "w": 92,
   "h": 223,
   "area": 6684
  },
  {
   "file": "assets/decor/signal/10.png",
   "w": 184,
   "h": 88,
   "area": 6117
  },
  {
   "file": "assets/decor/signal/6.png",
   "w": 40,
   "h": 218,
   "area": 5519
  },
  {
   "file": "assets/decor/signal/12.png",
   "w": 179,
   "h": 51,
   "area": 2343
  },
  {
   "file": "assets/decor/signal/11.png",
   "w": 150,
   "h": 54,
   "area": 1957
  }
 ],
 "srilanka": [
  {
   "file": "assets/decor/srilanka/19.png",
   "w": 178,
   "h": 171,
   "area": 12809
  },
  {
   "file": "assets/decor/srilanka/16.png",
   "w": 122,
   "h": 123,
   "area": 5123
  },
  {
   "file": "assets/decor/srilanka/25.png",
   "w": 113,
   "h": 76,
   "area": 3466
  },
  {
   "file": "assets/decor/srilanka/13.png",
   "w": 134,
   "h": 66,
   "area": 2861
  },
  {
   "file": "assets/decor/srilanka/21.png",
   "w": 164,
   "h": 59,
   "area": 2759
  },
  {
   "file": "assets/decor/srilanka/24.png",
   "w": 78,
   "h": 69,
   "area": 2271
  },
  {
   "file": "assets/decor/srilanka/22.png",
   "w": 104,
   "h": 57,
   "area": 2258
  },
  {
   "file": "assets/decor/srilanka/10.png",
   "w": 37,
   "h": 171,
   "area": 1928
  },
  {
   "file": "assets/decor/srilanka/20.png",
   "w": 78,
   "h": 49,
   "area": 1674
  },
  {
   "file": "assets/decor/srilanka/0.png",
   "w": 119,
   "h": 49,
   "area": 1527
  },
  {
   "file": "assets/decor/srilanka/2.png",
   "w": 88,
   "h": 92,
   "area": 1390
  },
  {
   "file": "assets/decor/srilanka/6.png",
   "w": 108,
   "h": 42,
   "area": 1256
  },
  {
   "file": "assets/decor/srilanka/1.png",
   "w": 102,
   "h": 43,
   "area": 1199
  },
  {
   "file": "assets/decor/srilanka/23.png",
   "w": 61,
   "h": 55,
   "area": 1164
  }
 ],
 "suzdal": [
  {
   "file": "assets/decor/suzdal/6.png",
   "w": 332,
   "h": 254,
   "area": 55041
  },
  {
   "file": "assets/decor/suzdal/4.png",
   "w": 248,
   "h": 299,
   "area": 38236
  },
  {
   "file": "assets/decor/suzdal/1.png",
   "w": 203,
   "h": 248,
   "area": 30471
  },
  {
   "file": "assets/decor/suzdal/3.png",
   "w": 188,
   "h": 237,
   "area": 27190
  },
  {
   "file": "assets/decor/suzdal/5.png",
   "w": 205,
   "h": 275,
   "area": 24942
  },
  {
   "file": "assets/decor/suzdal/10.png",
   "w": 261,
   "h": 129,
   "area": 19477
  },
  {
   "file": "assets/decor/suzdal/0.png",
   "w": 132,
   "h": 251,
   "area": 17932
  },
  {
   "file": "assets/decor/suzdal/9.png",
   "w": 179,
   "h": 191,
   "area": 17217
  },
  {
   "file": "assets/decor/suzdal/2.png",
   "w": 118,
   "h": 247,
   "area": 15276
  },
  {
   "file": "assets/decor/suzdal/12.png",
   "w": 241,
   "h": 92,
   "area": 13763
  },
  {
   "file": "assets/decor/suzdal/11.png",
   "w": 231,
   "h": 95,
   "area": 13667
  },
  {
   "file": "assets/decor/suzdal/8.png",
   "w": 143,
   "h": 97,
   "area": 3880
  },
  {
   "file": "assets/decor/suzdal/7.png",
   "w": 142,
   "h": 65,
   "area": 3201
  },
  {
   "file": "assets/decor/suzdal/13.png",
   "w": 102,
   "h": 57,
   "area": 2743
  }
 ],
 "tarusa": [
  {
   "file": "assets/decor/tarusa/1.png",
   "w": 269,
   "h": 325,
   "area": 55886
  },
  {
   "file": "assets/decor/tarusa/2.png",
   "w": 246,
   "h": 329,
   "area": 47018
  },
  {
   "file": "assets/decor/tarusa/3.png",
   "w": 336,
   "h": 208,
   "area": 34522
  },
  {
   "file": "assets/decor/tarusa/0.png",
   "w": 152,
   "h": 328,
   "area": 25189
  },
  {
   "file": "assets/decor/tarusa/5.png",
   "w": 241,
   "h": 136,
   "area": 22791
  },
  {
   "file": "assets/decor/tarusa/10.png",
   "w": 203,
   "h": 139,
   "area": 22176
  },
  {
   "file": "assets/decor/tarusa/4.png",
   "w": 180,
   "h": 151,
   "area": 18552
  },
  {
   "file": "assets/decor/tarusa/8.png",
   "w": 110,
   "h": 216,
   "area": 14811
  },
  {
   "file": "assets/decor/tarusa/9.png",
   "w": 161,
   "h": 180,
   "area": 14239
  },
  {
   "file": "assets/decor/tarusa/11.png",
   "w": 159,
   "h": 122,
   "area": 10214
  },
  {
   "file": "assets/decor/tarusa/7.png",
   "w": 93,
   "h": 270,
   "area": 6650
  },
  {
   "file": "assets/decor/tarusa/6.png",
   "w": 131,
   "h": 100,
   "area": 6457
  },
  {
   "file": "assets/decor/tarusa/14.png",
   "w": 106,
   "h": 80,
   "area": 4171
  },
  {
   "file": "assets/decor/tarusa/12.png",
   "w": 64,
   "h": 111,
   "area": 2993
  }
 ],
 "tent_night": [
  {
   "file": "assets/decor/tent_night/0.png",
   "w": 208,
   "h": 466,
   "area": 41540
  },
  {
   "file": "assets/decor/tent_night/6.png",
   "w": 544,
   "h": 170,
   "area": 37021
  },
  {
   "file": "assets/decor/tent_night/1.png",
   "w": 210,
   "h": 466,
   "area": 35501
  },
  {
   "file": "assets/decor/tent_night/3.png",
   "w": 196,
   "h": 328,
   "area": 32325
  },
  {
   "file": "assets/decor/tent_night/8.png",
   "w": 300,
   "h": 149,
   "area": 28799
  },
  {
   "file": "assets/decor/tent_night/7.png",
   "w": 376,
   "h": 145,
   "area": 27651
  },
  {
   "file": "assets/decor/tent_night/2.png",
   "w": 183,
   "h": 327,
   "area": 24425
  },
  {
   "file": "assets/decor/tent_night/9.png",
   "w": 306,
   "h": 110,
   "area": 21282
  },
  {
   "file": "assets/decor/tent_night/10.png",
   "w": 292,
   "h": 110,
   "area": 20544
  },
  {
   "file": "assets/decor/tent_night/4.png",
   "w": 223,
   "h": 153,
   "area": 18120
  },
  {
   "file": "assets/decor/tent_night/5.png",
   "w": 246,
   "h": 137,
   "area": 16060
  },
  {
   "file": "assets/decor/tent_night/12.png",
   "w": 89,
   "h": 103,
   "area": 5159
  },
  {
   "file": "assets/decor/tent_night/11.png",
   "w": 143,
   "h": 153,
   "area": 4571
  },
  {
   "file": "assets/decor/tent_night/13.png",
   "w": 82,
   "h": 83,
   "area": 2870
  }
 ],
 "thailand": [
  {
   "file": "assets/decor/thailand/5.png",
   "w": 358,
   "h": 233,
   "area": 44168
  },
  {
   "file": "assets/decor/thailand/6.png",
   "w": 331,
   "h": 193,
   "area": 43541
  },
  {
   "file": "assets/decor/thailand/8.png",
   "w": 356,
   "h": 166,
   "area": 32211
  },
  {
   "file": "assets/decor/thailand/2.png",
   "w": 240,
   "h": 303,
   "area": 26966
  },
  {
   "file": "assets/decor/thailand/0.png",
   "w": 216,
   "h": 323,
   "area": 23975
  },
  {
   "file": "assets/decor/thailand/1.png",
   "w": 262,
   "h": 305,
   "area": 23959
  },
  {
   "file": "assets/decor/thailand/3.png",
   "w": 216,
   "h": 239,
   "area": 22194
  },
  {
   "file": "assets/decor/thailand/12.png",
   "w": 244,
   "h": 161,
   "area": 18163
  },
  {
   "file": "assets/decor/thailand/13.png",
   "w": 182,
   "h": 160,
   "area": 14897
  },
  {
   "file": "assets/decor/thailand/4.png",
   "w": 149,
   "h": 227,
   "area": 14169
  },
  {
   "file": "assets/decor/thailand/11.png",
   "w": 271,
   "h": 77,
   "area": 11746
  },
  {
   "file": "assets/decor/thailand/7.png",
   "w": 269,
   "h": 75,
   "area": 11266
  },
  {
   "file": "assets/decor/thailand/15.png",
   "w": 142,
   "h": 78,
   "area": 4711
  },
  {
   "file": "assets/decor/thailand/9.png",
   "w": 227,
   "h": 139,
   "area": 4510
  }
 ],
 "thailand_ambulance": [
  {
   "file": "assets/decor/thailand_ambulance/0.png",
   "w": 830,
   "h": 519,
   "area": 326155
  }
 ],
 "thailand_birthday": [
  {
   "file": "assets/decor/thailand_birthday/3.png",
   "w": 239,
   "h": 287,
   "area": 23377
  },
  {
   "file": "assets/decor/thailand_birthday/5.png",
   "w": 285,
   "h": 248,
   "area": 21633
  },
  {
   "file": "assets/decor/thailand_birthday/1.png",
   "w": 211,
   "h": 174,
   "area": 15361
  },
  {
   "file": "assets/decor/thailand_birthday/6.png",
   "w": 142,
   "h": 268,
   "area": 13828
  },
  {
   "file": "assets/decor/thailand_birthday/0.png",
   "w": 193,
   "h": 180,
   "area": 13019
  },
  {
   "file": "assets/decor/thailand_birthday/9.png",
   "w": 194,
   "h": 175,
   "area": 12756
  },
  {
   "file": "assets/decor/thailand_birthday/10.png",
   "w": 201,
   "h": 178,
   "area": 12210
  },
  {
   "file": "assets/decor/thailand_birthday/2.png",
   "w": 199,
   "h": 211,
   "area": 12164
  },
  {
   "file": "assets/decor/thailand_birthday/8.png",
   "w": 110,
   "h": 246,
   "area": 11617
  },
  {
   "file": "assets/decor/thailand_birthday/18.png",
   "w": 139,
   "h": 90,
   "area": 3425
  },
  {
   "file": "assets/decor/thailand_birthday/13.png",
   "w": 76,
   "h": 124,
   "area": 3230
  },
  {
   "file": "assets/decor/thailand_birthday/12.png",
   "w": 164,
   "h": 72,
   "area": 3070
  },
  {
   "file": "assets/decor/thailand_birthday/19.png",
   "w": 89,
   "h": 84,
   "area": 2289
  },
  {
   "file": "assets/decor/thailand_birthday/11.png",
   "w": 144,
   "h": 50,
   "area": 2021
  }
 ],
 "tour": [
  {
   "file": "assets/decor/tour/2.png",
   "w": 298,
   "h": 330,
   "area": 66960
  },
  {
   "file": "assets/decor/tour/0.png",
   "w": 302,
   "h": 340,
   "area": 64464
  },
  {
   "file": "assets/decor/tour/6.png",
   "w": 352,
   "h": 196,
   "area": 38566
  },
  {
   "file": "assets/decor/tour/9.png",
   "w": 279,
   "h": 209,
   "area": 33973
  },
  {
   "file": "assets/decor/tour/10.png",
   "w": 291,
   "h": 204,
   "area": 29472
  },
  {
   "file": "assets/decor/tour/1.png",
   "w": 189,
   "h": 332,
   "area": 29100
  },
  {
   "file": "assets/decor/tour/8.png",
   "w": 269,
   "h": 235,
   "area": 26768
  },
  {
   "file": "assets/decor/tour/5.png",
   "w": 285,
   "h": 204,
   "area": 20380
  },
  {
   "file": "assets/decor/tour/3.png",
   "w": 132,
   "h": 305,
   "area": 12441
  },
  {
   "file": "assets/decor/tour/4.png",
   "w": 152,
   "h": 209,
   "area": 11977
  },
  {
   "file": "assets/decor/tour/7.png",
   "w": 172,
   "h": 132,
   "area": 8184
  },
  {
   "file": "assets/decor/tour/12.png",
   "w": 94,
   "h": 65,
   "area": 2328
  },
  {
   "file": "assets/decor/tour/11.png",
   "w": 74,
   "h": 59,
   "area": 1877
  }
 ],
 "tula": [
  {
   "file": "assets/decor/tula/4.png",
   "w": 702,
   "h": 284,
   "area": 74679
  },
  {
   "file": "assets/decor/tula/3.png",
   "w": 221,
   "h": 246,
   "area": 30358
  },
  {
   "file": "assets/decor/tula/2.png",
   "w": 220,
   "h": 247,
   "area": 30348
  },
  {
   "file": "assets/decor/tula/11.png",
   "w": 292,
   "h": 151,
   "area": 27089
  },
  {
   "file": "assets/decor/tula/12.png",
   "w": 277,
   "h": 103,
   "area": 18611
  },
  {
   "file": "assets/decor/tula/1.png",
   "w": 139,
   "h": 251,
   "area": 16367
  },
  {
   "file": "assets/decor/tula/0.png",
   "w": 139,
   "h": 252,
   "area": 16173
  },
  {
   "file": "assets/decor/tula/13.png",
   "w": 220,
   "h": 88,
   "area": 11948
  },
  {
   "file": "assets/decor/tula/5.png",
   "w": 131,
   "h": 198,
   "area": 11866
  },
  {
   "file": "assets/decor/tula/7.png",
   "w": 137,
   "h": 154,
   "area": 10560
  },
  {
   "file": "assets/decor/tula/9.png",
   "w": 247,
   "h": 134,
   "area": 8217
  },
  {
   "file": "assets/decor/tula/8.png",
   "w": 249,
   "h": 128,
   "area": 7543
  },
  {
   "file": "assets/decor/tula/6.png",
   "w": 83,
   "h": 172,
   "area": 4546
  },
  {
   "file": "assets/decor/tula/10.png",
   "w": 124,
   "h": 85,
   "area": 3778
  }
 ],
 "turkey": [
  {
   "file": "assets/decor/turkey/5.png",
   "w": 261,
   "h": 241,
   "area": 38873
  },
  {
   "file": "assets/decor/turkey/11.png",
   "w": 305,
   "h": 157,
   "area": 28222
  },
  {
   "file": "assets/decor/turkey/7.png",
   "w": 203,
   "h": 216,
   "area": 28045
  },
  {
   "file": "assets/decor/turkey/6.png",
   "w": 200,
   "h": 236,
   "area": 26748
  },
  {
   "file": "assets/decor/turkey/3.png",
   "w": 220,
   "h": 241,
   "area": 24742
  },
  {
   "file": "assets/decor/turkey/0.png",
   "w": 242,
   "h": 323,
   "area": 22941
  },
  {
   "file": "assets/decor/turkey/2.png",
   "w": 220,
   "h": 305,
   "area": 22356
  },
  {
   "file": "assets/decor/turkey/4.png",
   "w": 203,
   "h": 231,
   "area": 21634
  },
  {
   "file": "assets/decor/turkey/12.png",
   "w": 268,
   "h": 111,
   "area": 16104
  },
  {
   "file": "assets/decor/turkey/13.png",
   "w": 244,
   "h": 100,
   "area": 14568
  },
  {
   "file": "assets/decor/turkey/1.png",
   "w": 75,
   "h": 322,
   "area": 13683
  },
  {
   "file": "assets/decor/turkey/8.png",
   "w": 162,
   "h": 161,
   "area": 12443
  },
  {
   "file": "assets/decor/turkey/9.png",
   "w": 173,
   "h": 146,
   "area": 11517
  },
  {
   "file": "assets/decor/turkey/10.png",
   "w": 123,
   "h": 154,
   "area": 10404
  }
 ],
 "vietnam": [
  {
   "file": "assets/decor/vietnam/2.png",
   "w": 284,
   "h": 310,
   "area": 36429
  },
  {
   "file": "assets/decor/vietnam/0.png",
   "w": 277,
   "h": 347,
   "area": 27891
  },
  {
   "file": "assets/decor/vietnam/7.png",
   "w": 354,
   "h": 130,
   "area": 25948
  },
  {
   "file": "assets/decor/vietnam/6.png",
   "w": 217,
   "h": 188,
   "area": 22675
  },
  {
   "file": "assets/decor/vietnam/5.png",
   "w": 208,
   "h": 220,
   "area": 19800
  },
  {
   "file": "assets/decor/vietnam/1.png",
   "w": 235,
   "h": 316,
   "area": 18259
  },
  {
   "file": "assets/decor/vietnam/8.png",
   "w": 255,
   "h": 162,
   "area": 16836
  },
  {
   "file": "assets/decor/vietnam/15.png",
   "w": 311,
   "h": 100,
   "area": 16436
  },
  {
   "file": "assets/decor/vietnam/14.png",
   "w": 194,
   "h": 124,
   "area": 13943
  },
  {
   "file": "assets/decor/vietnam/16.png",
   "w": 281,
   "h": 82,
   "area": 11945
  },
  {
   "file": "assets/decor/vietnam/11.png",
   "w": 168,
   "h": 96,
   "area": 7378
  },
  {
   "file": "assets/decor/vietnam/13.png",
   "w": 240,
   "h": 90,
   "area": 6817
  },
  {
   "file": "assets/decor/vietnam/12.png",
   "w": 178,
   "h": 93,
   "area": 5583
  },
  {
   "file": "assets/decor/vietnam/18.png",
   "w": 88,
   "h": 111,
   "area": 3256
  }
 ],
 "vietnam_masha": [
  {
   "file": "assets/decor/vietnam_masha/8.png",
   "w": 398,
   "h": 172,
   "area": 31883
  },
  {
   "file": "assets/decor/vietnam_masha/5.png",
   "w": 429,
   "h": 137,
   "area": 31662
  },
  {
   "file": "assets/decor/vietnam_masha/9.png",
   "w": 374,
   "h": 136,
   "area": 16893
  },
  {
   "file": "assets/decor/vietnam_masha/0.png",
   "w": 232,
   "h": 257,
   "area": 13789
  },
  {
   "file": "assets/decor/vietnam_masha/1.png",
   "w": 186,
   "h": 149,
   "area": 11970
  },
  {
   "file": "assets/decor/vietnam_masha/11.png",
   "w": 205,
   "h": 122,
   "area": 9875
  },
  {
   "file": "assets/decor/vietnam_masha/2.png",
   "w": 157,
   "h": 242,
   "area": 9732
  },
  {
   "file": "assets/decor/vietnam_masha/12.png",
   "w": 218,
   "h": 98,
   "area": 9286
  },
  {
   "file": "assets/decor/vietnam_masha/15.png",
   "w": 97,
   "h": 64,
   "area": 2955
  },
  {
   "file": "assets/decor/vietnam_masha/14.png",
   "w": 135,
   "h": 69,
   "area": 2582
  },
  {
   "file": "assets/decor/vietnam_masha/13.png",
   "w": 104,
   "h": 48,
   "area": 1972
  },
  {
   "file": "assets/decor/vietnam_masha/7.png",
   "w": 140,
   "h": 115,
   "area": 1769
  },
  {
   "file": "assets/decor/vietnam_masha/3.png",
   "w": 93,
   "h": 135,
   "area": 1446
  },
  {
   "file": "assets/decor/vietnam_masha/16.png",
   "w": 79,
   "h": 56,
   "area": 1371
  }
 ]
};
